# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your 
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step 
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release

on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install CSQ CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          INSTALL_DIR="$HOME/.local/bin"
          mkdir -p "$INSTALL_DIR"
          echo "$INSTALL_DIR" >> $GITHUB_PATH
          
          # Download csq CLI from contentsquare/platform_csq-go-cli
          gh release download -R contentsquare/platform_csq-go-cli -p "*$(uname | tr A-Z a-z)_$(uname -m | sed 's/x86_64/amd64/').tar.gz"
          
          # Extract csq binary
          tar xzvf "$(ls -t platform_csq-go-cli_*.tar.gz | head -n1)" -C "$INSTALL_DIR" csq
          
          # Verify installation
          "$INSTALL_DIR/csq" --version

      - name: Retrieve secrets from Vault
        uses: ContentSquare/action-vault@v1
        with:
          environment: mgmt
          secrets: |
            secrets_platform/data/mgmt/eu-west-1/terralist/gpg-signing-key private_key | GPG_PRIVATE_KEY ;
            secrets_platform/data/mgmt/eu-west-1/terralist/gpg-signing-key passphrase | GPG_PASSPHRASE ;
            secrets_platform/data/mgmt/eu-west-1/terralist/api-key key | TERRALIST_API_KEY

      - name: Set proper permissions on .gnupg
        run: sudo chown -R "$(whoami)":"$(whoami)" /tmp/.gnupg

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        id: import_gpg
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Upload provider to Terralist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          csq terralist provider release \
            --provider $(echo ${{ github.repository }} | sed 's/.*terraform-provider-//') \
            --repo $(echo ${{ github.repository }} | cut -d '/' -f2) \
            --owner $(echo ${{ github.repository }} | cut -d '/' -f1) \
            --tag ${{ github.ref_name }}
